version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: discodeit-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Seoul"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - discodeit-network

  app:
    image: discodeit:local
    container_name: discodeit-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_VERSION: ${PROJECT_VERSION}
    volumes:
      - ./.discodeit/storage:/app/.discodeit/storage
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - discodeit-network

volumes:
  postgres-data:

networks:
  discodeit-network:
    driver: bridge
